### ISSUE TITLE
CLI scd utility crashes when trying to disassemble RDT file

### ISSUE THREAD

**Issue by ZeroAnarchy** [IntelOrca/biohazard-utils#2]
Commit https://github.com/IntelOrca/biohazard-utils/commit/aa81a6a598e7f14ba91f47d8fc1aeac2d3d3a396 fixed RDT assembly with modified SCD script, but now the program stopped recognizing the "-x" argument.

``` 
scd -x ROOM1000.RDT -v 2
```
``` 
 System.IO.FileNotFoundException: File '...\scd\bin\Release\net472\-x' not found.
  IntelOrca.Scd.Program.Main(String[] args) in ...\scd\Program.cs:line 42
```

I tried to message you in Discord about this, but unfortunately you did not respond to my messages.

**Comment by IntelOrca** [comment]
New command line parsing library is now being used.
`-v` has been changed to `--game`
